include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    sort_constructors_first: false
    prefer_const_constructors: false
    # always_specify_types: true
    # public_member_api_docs: true
    # lines_longer_than_80_chars: true
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
